## Imports

In [1]:
import sqlite3
import glob
import time
import itertools 

import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from tqdm.notebook import tqdm

/var/folders/m8/kq3tbvsx79n47wprd2zwv5hm0000gn/T/ipykernel_16965/1025221560.py:7: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

_____

## 1. Data Ingestion 

Read the data from the database.

In [2]:
annotated_dbs = glob.glob(f'./dataset/fang_system/*.json')

print("Found the following dbs : " , annotated_dbs)

synchronous_annotators = ['group_1' , 'group_2'] 
asynchronous_annotators = ['async_1' , 'async_2' , 'async_3'] 
annotators = synchronous_annotators + asynchronous_annotators
annotator2df = {}

for db_path in  annotated_dbs : 
    merged_df = pd.read_json(db_path)

    for key in annotators : 
        if key in db_path : 
            annotator2df[key] = merged_df

Found the following dbs :  ['./dataset/fang_system/async_1.json', './dataset/fang_system/async_1_selected.json', './dataset/fang_system/group_1.json', './dataset/fang_system/group_2.json', './dataset/fang_system/async_2.json', './dataset/fang_system/async_3.json']

### 1.a. Random Sampling rows for manual annotations

Pull 200 samples from both synchronous and asynchronous groups to manually review label quality. Pulling from top 25th percentile is done later.

In [3]:
synchronous_random_samples = []
asynchronous_random_samples = []

for annotator , df in annotator2df.items(): 
    if annotator in synchronous_annotators: 
        synchronous_random_samples.append(df.sample(n=100))
    if annotator in asynchronous_annotators: 
        asynchronous_random_samples.append(df.sample(n=67))

res_df = pd.concat(synchronous_random_samples)
async_df = pd.concat(asynchronous_random_samples)

res_df = res_df[['text' , 'name']].sample(frac=1)
async_df = async_df[['text' , 'name']].sample(frac=1)

# res_df.to_csv('./dataset/generated_samples/fang_sync_sample_all.csv' , index=False, sep='\t')
# async_df.to_csv('./dataset/generated_samples/fang_async_sample_all.csv' , index=False, sep='\t')

_____

## 2. Jaccard Similarity 

Jaccard similarity for two themes is calculated by the union of their documents divided by the intersection of their documents.

In [4]:
results = []

for anno_1 , anno_2 in itertools.permutations(annotators , 2): 
    anno_1_themes = annotator2df[anno_1]['name'].unique()
    anno_2_themes = annotator2df[anno_2]['name'].unique()
    for anno_1_theme , anno_2_theme in itertools.product(anno_1_themes , anno_2_themes): 
        result = {'anno_1' : anno_1 , 
                  'anno_2' : anno_2 , 
                  'anno_1_theme' : anno_1_theme ,
                  'anno_2_theme' : anno_2_theme}
        anno_1_tweet_ids = set(annotator2df[anno_1][annotator2df[anno_1]['name']==anno_1_theme]['tweet_id'])
        anno_2_tweet_ids = set(annotator2df[anno_2][annotator2df[anno_2]['name']==anno_2_theme]['tweet_id'])
        intersection = anno_1_tweet_ids.intersection(anno_2_tweet_ids)
        union = anno_1_tweet_ids.union(anno_2_tweet_ids)
        jaccard_sim = len(intersection) / len(union)
        result['jaccard_sim'] = jaccard_sim
        results.append(result)

jaccard_df = pd.DataFrame(results)

### 2.a. Getting max jaccard similarity for synchronous experiments

In [5]:
max_jacc_sims = []
filtered_df = jaccard_df[
    (jaccard_df["anno_1"].isin(synchronous_annotators))
    & (jaccard_df["anno_2"].isin(synchronous_annotators))
]

for anno_1_theme in filtered_df["anno_1_theme"].unique():
    if (
        ("kmeans" not in anno_1_theme.lower())
        and ("Unexplainable" not in anno_1_theme.strip())
        and ("topic" not in anno_1_theme.strip())
        and ("Unknown" not in anno_1_theme.strip())
    ):
        theme_filtered_df = filtered_df[
            (filtered_df["anno_1_theme"] == anno_1_theme)
            & ~(filtered_df["anno_2_theme"].str.contains("Kmeans"))
            & ~(filtered_df["anno_2_theme"].str.contains("Unexplainable"))
            & ~(filtered_df["anno_2_theme"].str.contains("topic"))
            & ~(filtered_df["anno_2_theme"].str.contains("Unknown"))
        ]
        max_jacc_sims.append(
            theme_filtered_df.loc[(theme_filtered_df["jaccard_sim"].idxmax())].to_dict()
        )
res_df = pd.DataFrame(max_jacc_sims)

print("Synchronous Jaccard Similarity")
print(f"Average Max Jaccard Similarity: {res_df['jaccard_sim'].mean():.2f}")
print(f"Standard Deviation of Jaccard Similarity: {res_df['jaccard_sim'].std():.2f}")
print(res_df.count())

Synchronous Jaccard Similarity
Average Max Jaccard Similarity: 0.37
Standard Deviation of Jaccard Similarity: 0.31
anno_1          29
anno_2          29
anno_1_theme    29
anno_2_theme    29
jaccard_sim     29
dtype: int64

In [6]:
# To view individual similarities
res_df

,anno_1,anno_2,anno_1_theme,anno_2_theme,jaccard_sim
0,group_1,group_2,AntiGunBan,gun rights,0.422222
1,group_1,group_2,EnvironmentalConservation,climate action,0.562862
2,group_1,group_2,SchoolBoardFinances/GasInfrastructure,inflation,0.200929
3,group_1,group_2,AntiGridDeregulation/PoliticalActionAds,gun rights,0.068966
4,group_1,group_2,CleanEnergyGoals,renewables,0.672467
5,group_1,group_2,BellbrookSugarcreekConservativeElections,anti-woke,0.675926
6,group_1,group_2,ConservativePoliticsEvents,indigenous activism,0.240506
7,group_1,group_2,TPUSAAd,TPUSA,0.821429
8,group_1,group_2,DomesticOilAndGasProduction,inflation,0.056522
9,group_1,group_2,ClimateChange,climate action,0.060784
10,group_1,group_2,Pipeline,climate action,0.004578
11,group_1,group_2,BuildBackBetterAct,pro oil and natural gas,0.494200
12,group_1,group_2,AntiGridDeregulation,pro oil and natural gas,0.011468
13,group_1,group_2,LiberalTaxHikes,inflation,0.146199
14,group_1,group_2,NativeAmericanCulturalPreservation,indigenous activism,0.255319
15,group_1,group_2,OilTheft/ClimateLeader,organized cooking oil theft,0.950000
16,group_1,group_2,NaturalGasIncentive/CleanEnergyPetition,renewables,0.002356
17,group_1,group_2,CleanEnergyProjects,renewables,0.000785
18,group_1,group_2,ColoradoAirQuality/SupportingBlackWomen,indigenous activism,0.021277
19,group_2,group_1,gun rights,AntiGunBan,0.422222
20,group_2,group_1,climate action,EnvironmentalConservation,0.562862
21,group_2,group_1,renewables,CleanEnergyGoals,0.672467
22,group_2,group_1,inflation,SchoolBoardFinances/GasInfrastructure,0.200929
23,group_2,group_1,anti-woke,BellbrookSugarcreekConservativeElections,0.675926
24,group_2,group_1,organized cooking oil theft,OilTheft/ClimateLeader,0.950000
25,group_2,group_1,indigenous activism,NativeAmericanCulturalPreservation,0.255319
26,group_2,group_1,pro oil and natural gas,BuildBackBetterAct,0.494200
27,group_2,group_1,TPUSA,TPUSAAd,0.821429
28,group_2,group_1,conservative school board,SchoolBoardFinances/GasInfrastructure,0.020000

### 2.b. Getting max jaccard similarity for asynchronous experiments

In [7]:
max_jacc_sims = []
filtered_df = jaccard_df[
    (jaccard_df["anno_1"].isin(asynchronous_annotators))
    & (jaccard_df["anno_2"].isin(asynchronous_annotators))
]
for anno_1_theme in filtered_df["anno_1_theme"].unique():
    if (
        ("kmeans" not in anno_1_theme.lower())
        and ("Unexplainable" not in anno_1_theme.strip())
        and ("topic" not in anno_1_theme.strip())
        and ("Unknown" not in anno_1_theme.strip())
    ):
        theme_filtered_df = filtered_df[
            (filtered_df["anno_1_theme"] == anno_1_theme)
            & ~(filtered_df["anno_2_theme"].str.contains("Kmeans"))
            & ~(filtered_df["anno_2_theme"].str.contains("Unexplainable"))
            & ~(filtered_df["anno_2_theme"].str.contains("topic"))
            & ~(filtered_df["anno_2_theme"].str.contains("Unknown"))
        ]
        max_jacc_sims.append(
            theme_filtered_df.loc[(theme_filtered_df["jaccard_sim"].idxmax())].to_dict()
        )
res_df = pd.DataFrame(max_jacc_sims)

print("Asynchronous Jaccard Similarity")
print(f"Average Max Jaccard Similarity: {res_df['jaccard_sim'].mean():.2f}")
print(f"Standard Deviation of Jaccard Similarity: {res_df['jaccard_sim'].std():.2f}")

Asynchronous Jaccard Similarity
Average Max Jaccard Similarity: 0.58
Standard Deviation of Jaccard Similarity: 0.29

In [8]:
# To view individual similarities
res_df

,anno_1,anno_2,anno_1_theme,anno_2_theme,jaccard_sim
0,async_3,async_2,AntiGunBan,pro-2A,0.581395
1,async_1,async_3,AntiWoke,AntiLiberalElectionCandidates,0.695035
2,async_1,async_3,ProtectEnvironment,SaveEnvironment,0.724792
3,async_1,async_3,CleanEnergyWorks,ProRenewableEnergy,0.656859
4,async_1,async_2,ActionAgainstDemSpending,criticism of liberal tax policy,0.767528
5,async_1,async_3,IndigenousAndBlackAdvocacy,MinorityGroupWomenAdvocacy,0.673469
6,async_1,async_2,PassBidenAct,promoting legislation against climate change,0.834116
7,async_1,async_3,AntiOilPolitician,ProCleanEnergyPolitician,0.754601
8,async_1,async_2,AntiPropertyTax,discussing problems with school board,0.875000
9,async_1,async_2,ProUSOilIndustry,criticism for disfavoring US ONG production,0.574468
10,async_1,async_3,ProtectRivers,DonationsForProRiverPoliticians,0.400000
11,async_1,async_2,TPUSAAd,promoting news and oped program,0.945455
12,async_1,async_3,EVCharging,SaveEnvironment,0.000759
13,async_1,async_3,OilTheft,BioFuelTheft,0.800000
14,async_2,async_3,pro-2A,AntiGunBan,0.581395
15,async_2,async_1,donations for climate change,ProtectEnvironment,0.675182
16,async_2,async_1,solar energy,AntiGunBan,0.106965
17,async_2,async_3,advocating for city level politics,AntiLiberalElectionCandidates,0.832258
18,async_2,async_3,political activism to oppose climate change,BioFuelTheft,0.952381
19,async_2,async_1,criticism of liberal tax policy,ActionAgainstDemSpending,0.767528
20,async_2,async_1,indigenous climate justice,IndigenousAndBlackAdvocacy,0.566667
21,async_2,async_1,promoting legislation against climate change,PassBidenAct,0.834116
22,async_2,async_1,pros of wind and solar energy,CleanEnergyWorks,0.108280
23,async_2,async_1,criticism for disfavoring US ONG production,ProUSOilIndustry,0.574468
24,async_2,async_3,kudos for confronting ONG emissions,ProCleanEnergyPolitician,0.538188
25,async_2,async_3,access to water and promoting renewable energy,DonationsForProRiverPoliticians,0.529412
26,async_2,async_1,discussing problems with school board,AntiPropertyTax,0.875000
27,async_2,async_1,promoting news and oped program,TPUSAAd,0.945455
28,async_3,async_1,BidenPolicies,ProUSOilIndustry,0.085271
29,async_3,async_1,SaveEnvironment,ProtectEnvironment,0.724792
30,async_3,async_2,AntiLiberalElectionCandidates,advocating for city level politics,0.832258
31,async_3,async_1,RisingEnergyCost,ActionAgainstDemSpending,0.126359
32,async_3,async_1,ProRenewableEnergy,CleanEnergyWorks,0.656859
33,async_3,async_2,PoliticalLeadershipTraining,solar energy,0.074074
34,async_3,async_2,BioFuelTheft,political activism to oppose climate change,0.952381
35,async_3,async_1,ProUSOil,ActionAgainstDemSpending,0.231884
36,async_3,async_1,MinorityGroupWomenAdvocacy,IndigenousAndBlackAdvocacy,0.673469
37,async_3,async_2,DonationsForProRiverPoliticians,access to water and promoting renewable energy,0.529412
38,async_3,async_2,SupportForBuildBackBetterAct,promoting legislation against climate change,0.615137
39,async_3,async_1,WaterPollutionAndContamination,ProtectEnvironment,0.010678
40,async_3,async_1,ProCleanEnergyPolitician,AntiOilPolitician,0.754601
41,async_3,async_1,TPUSALiveAd,TPUSAAd,0.867925
42,async_3,async_1,AntiLiberalSpending,ActionAgainstDemSpending,0.197289
43,async_3,async_2,EnergyInfrastructureProjects,pros of wind and solar energy,0.076190

______

## 3. Centroid Cosine Similarity

### 3.a. Loading SBERT Vectors

In [9]:
sbert_vectors = np.load('./dataset/sbert.npy')

### 3.b. Calculating centroids for sync + async experiments

In [10]:
results = []

for annotator, df in annotator2df.items():
    cosine_sims = []
    themes = []
    for i, theme in enumerate(df["name"].unique()):
        if (
            ("kmeans" not in theme.lower())
            and ("Unexplainable" not in theme.strip())
            and ("topic" not in theme.strip())
            and ("Unknown" not in theme.strip())
        ):
            result = {"annotator": annotator}
            ids = df[df["name"] == theme]["tweet_id"].tolist()
            result["theme"] = theme
            theme_vectors = sbert_vectors[ids]
            theme_centroid = np.average(theme_vectors, axis=0, keepdims=True)

            result["theme_centroid"] = theme_centroid
            result["theme_vectors"] = theme_vectors

            dot_prod = np.dot(theme_centroid, theme_vectors.T).squeeze(0)
            dot_prod = np.expand_dims(dot_prod, axis=-1)

            norm = np.linalg.norm(theme_vectors, axis=1, keepdims=True)
            cosine_sim = dot_prod / norm
            result["cosine_sim"] = cosine_sim
            results.append(result)

### 3.c. Calculating synchronous centroid cosine similarity

In [11]:
cosine_sim_results = []

for anno_1, anno_2 in itertools.permutations(synchronous_annotators, 2):
    anno_1_results = [r for r in results if r["annotator"] == anno_1]
    anno_2_results = [r for r in results if r["annotator"] == anno_2]
    for anno_1_result in anno_1_results:
        for anno_2_result in anno_2_results:
            if (
                ("kmeans" not in anno_1_result["theme"].lower())
                and ("Unexplainable" not in anno_1_result["theme"].strip())
                and ("topic" not in anno_1_result["theme"].strip())
                and ("Unknown" not in anno_1_result["theme"].strip())
                and ("kmeans" not in anno_2_result["theme"].lower())
                and ("Unexplainable" not in anno_2_result["theme"].strip())
                and ("topic" not in anno_2_result["theme"].strip())
                and ("Unknown" not in anno_2_result["theme"].strip())
            ):
                cosine_sim = cosine_similarity(
                    anno_1_result["theme_centroid"], anno_2_result["theme_centroid"]
                )
                cosine_sim_result = {
                    "anno_1": anno_1,
                    "anno_2": anno_2,
                    "anno_1_theme": anno_1_result["theme"],
                    "anno_2_theme": anno_2_result["theme"],
                    "cosine_sim": cosine_sim.squeeze(),
                }
                cosine_sim_results.append(cosine_sim_result)

cosine_sim_df = pd.DataFrame(cosine_sim_results)

In [12]:
max_cosine_sims = []

for anno_1, anno_2 in itertools.permutations(synchronous_annotators, 2):
    filtered_df = cosine_sim_df[
        (cosine_sim_df["anno_1"] == anno_1) & (cosine_sim_df["anno_2"] == anno_2)
    ]
    for anno_1_theme in filtered_df["anno_1_theme"].unique():
        if (
            ("kmeans" not in anno_1_result["theme"].lower())
            and ("Unexplainable" not in anno_1_result["theme"].strip())
            and ("topic" not in anno_1_result["theme"].strip())
            and ("Unknown" not in anno_1_result["theme"].strip())
            and ("kmeans" not in anno_2_result["theme"].lower())
            and ("Unexplainable" not in anno_2_result["theme"].strip())
            and ("topic" not in anno_2_result["theme"].strip())
            and ("Unknown" not in anno_2_result["theme"].strip())
        ):
            theme_filtered_df = filtered_df[
                (filtered_df["anno_1_theme"] == anno_1_theme)
                & ~(filtered_df["anno_2_theme"].str.contains("Kmeans"))
                & ~(filtered_df["anno_2_theme"].str.contains("Unknown"))
            ]
            max_cosine_sims.append(
                theme_filtered_df.loc[
                    (theme_filtered_df["cosine_sim"].idxmax())
                ].to_dict()
            )

res_df = pd.DataFrame(max_cosine_sims)


print("Synchronous Centroid Cosine Similarity")
print(f"Average Max Centroid Cosine Similarity: {res_df['cosine_sim'].mean():.2f}")
print(
    f"Standard Deviation of Centroid Cosine Similarity: {res_df['cosine_sim'].std():.2f}"
)
print(res_df.count())

Synchronous Centroid Cosine Similarity
Average Max Centroid Cosine Similarity: 0.89
Standard Deviation of Centroid Cosine Similarity: 0.14
anno_1          29
anno_2          29
anno_1_theme    29
anno_2_theme    29
cosine_sim      29
dtype: int64

In [13]:
# To view individual similarities
res_df

,anno_1,anno_2,anno_1_theme,anno_2_theme,cosine_sim
0,group_1,group_2,AntiGunBan,gun rights,0.97422516
1,group_1,group_2,EnvironmentalConservation,climate action,0.9917236
2,group_1,group_2,SchoolBoardFinances/GasInfrastructure,inflation,0.9255009
3,group_1,group_2,AntiGridDeregulation/PoliticalActionAds,gun rights,0.80143815
4,group_1,group_2,CleanEnergyGoals,renewables,0.99667275
5,group_1,group_2,BellbrookSugarcreekConservativeElections,anti-woke,0.9893303
6,group_1,group_2,ConservativePoliticsEvents,indigenous activism,0.9292284
7,group_1,group_2,TPUSAAd,TPUSA,0.99082446
8,group_1,group_2,DomesticOilAndGasProduction,inflation,0.89372194
9,group_1,group_2,ClimateChange,climate action,0.8998476
10,group_1,group_2,Pipeline,inflation,0.70126855
11,group_1,group_2,BuildBackBetterAct,pro oil and natural gas,0.98014677
12,group_1,group_2,AntiGridDeregulation,renewables,0.7645365
13,group_1,group_2,LiberalTaxHikes,inflation,0.94421315
14,group_1,group_2,NativeAmericanCulturalPreservation,indigenous activism,0.8450005
15,group_1,group_2,OilTheft/ClimateLeader,organized cooking oil theft,0.9985639
16,group_1,group_2,NaturalGasIncentive/CleanEnergyPetition,inflation,0.5633087
17,group_1,group_2,CleanEnergyProjects,renewables,0.6881654
18,group_1,group_2,ColoradoAirQuality/SupportingBlackWomen,indigenous activism,0.52675766
19,group_2,group_1,gun rights,AntiGunBan,0.97422516
20,group_2,group_1,climate action,EnvironmentalConservation,0.9917236
21,group_2,group_1,renewables,CleanEnergyGoals,0.99667275
22,group_2,group_1,inflation,LiberalTaxHikes,0.94421315
23,group_2,group_1,anti-woke,BellbrookSugarcreekConservativeElections,0.9893303
24,group_2,group_1,organized cooking oil theft,OilTheft/ClimateLeader,0.9985639
25,group_2,group_1,indigenous activism,ConservativePoliticsEvents,0.9292284
26,group_2,group_1,pro oil and natural gas,BuildBackBetterAct,0.98014677
27,group_2,group_1,TPUSA,TPUSAAd,0.99082446
28,group_2,group_1,conservative school board,SchoolBoardFinances/GasInfrastructure,0.7323413

### 3.d. Calculating asynchronous centroid cosine similarity

In [14]:
cosine_sim_results = []

for anno_1, anno_2 in itertools.permutations(asynchronous_annotators, 2):
    anno_1_results = [r for r in results if r["annotator"] == anno_1]
    anno_2_results = [r for r in results if r["annotator"] == anno_2]
    for anno_1_result in anno_1_results:
        for anno_2_result in anno_2_results:
            if (
                ("kmeans" not in anno_1_result["theme"].lower())
                and ("Unexplainable" not in anno_1_result["theme"].strip())
                and ("topic" not in anno_1_result["theme"].strip())
                and ("Unknown" not in anno_1_result["theme"].strip())
                and ("kmeans" not in anno_2_result["theme"].lower())
                and ("Unexplainable" not in anno_2_result["theme"].strip())
                and ("topic" not in anno_2_result["theme"].strip())
                and ("Unknown" not in anno_2_result["theme"].strip())
            ):
                cosine_sim = cosine_similarity(
                    anno_1_result["theme_centroid"], anno_2_result["theme_centroid"]
                )
                cosine_sim_result = {
                    "anno_1": anno_1,
                    "anno_2": anno_2,
                    "anno_1_theme": anno_1_result["theme"],
                    "anno_2_theme": anno_2_result["theme"],
                    "cosine_sim": cosine_sim.squeeze(),
                }
                cosine_sim_results.append(cosine_sim_result)

cosine_sim_df = pd.DataFrame(cosine_sim_results)

In [15]:
max_cosine_sims = []

for anno_1, anno_2 in itertools.permutations(asynchronous_annotators, 2):
    filtered_df = cosine_sim_df[
        (cosine_sim_df["anno_1"] == anno_1) & (cosine_sim_df["anno_2"] == anno_2)
    ]
    for anno_1_theme in filtered_df["anno_1_theme"].unique():
        if (
            ("kmeans" not in anno_1_theme.lower())
            and ("unexplainable" not in anno_1_theme.lower())
            and ("topic" not in anno_1_theme.lower())
            and ("unknown" not in anno_1_theme.lower())
        ):
            theme_filtered_df = filtered_df[
                (filtered_df["anno_1_theme"] == anno_1_theme)
                & ~(filtered_df["anno_2_theme"].str.contains("Kmeans"))
                & ~(filtered_df["anno_2_theme"].str.contains("Unknown"))
            ]
            max_cosine_sims.append(
                theme_filtered_df.loc[
                    (theme_filtered_df["cosine_sim"].idxmax())
                ].to_dict()
            )

res_df = pd.DataFrame(max_cosine_sims)

print("Asynchronous Centroid Cosine Similarity")
print(f"Average Max Centroid Cosine Similarity: {res_df['cosine_sim'].mean():.2f}")
print(
    f"Standard Deviation of Centroid Cosine Similarity: {res_df['cosine_sim'].std():.2f}"
)
print(res_df.count())

Asynchronous Centroid Cosine Similarity
Average Max Centroid Cosine Similarity: 0.93
Standard Deviation of Centroid Cosine Similarity: 0.12
anno_1          92
anno_2          92
anno_1_theme    92
anno_2_theme    92
cosine_sim      92
dtype: int64

In [16]:
# To view individual similarities
res_df

,anno_1,anno_2,anno_1_theme,anno_2_theme,cosine_sim
0,async_1,async_2,AntiGunBan,pro-2A,0.9608255
1,async_1,async_2,AntiWoke,advocating for city level politics,0.9899468
2,async_1,async_2,ProtectEnvironment,donations for climate change,0.9940119
3,async_1,async_2,CleanEnergyWorks,pros of wind and solar energy,0.9248527
4,async_1,async_2,ActionAgainstDemSpending,criticism of liberal tax policy,0.99899626
...,...,...,...,...,...
87,async_3,async_2,ProCleanEnergyPolitician,kudos for confronting ONG emissions,0.9884269
88,async_3,async_2,TPUSALiveAd,promoting news and oped program,0.9919358
89,async_3,async_2,AntiLiberalSpending,criticism of liberal tax policy,0.8940756
90,async_3,async_2,AntiPropertyTax,discussing problems with school board,0.8627924
91,async_3,async_2,EnergyInfrastructureProjects,pros of wind and solar energy,0.8213408

____

## 4. Group Average Cosine Similarity

In [17]:
results = {}
annotators = []

for annotator, df in annotator2df.items():
    results[annotator] = {}
    annotators.append(annotator)
    for i, theme in enumerate(df["name"].unique()):
        if (
            ("kmeans" not in theme.lower())
            and ("Unexplainable" not in theme.strip())
            and ("topic" not in theme.strip())
            and ("Unknown" not in theme.strip())
        ):
            ids = df[df["name"] == theme]["tweet_id"].tolist()
            theme_vectors = sbert_vectors[ids]
            results[annotator][theme] = theme_vectors

### 4.a. Calculating Group Average Similarities

In [18]:
global_average_sims = []
total_combos = len(list(itertools.combinations_with_replacement(annotators, 2)))

for ctr , (anno1 , anno2) in enumerate(itertools.combinations_with_replacement(annotators, 2)):
  anno1_themes = results[anno1]
  anno2_themes = results[anno2]
  for anno1_theme, anno1_theme_vectors in anno1_themes.items():
    for anno2_theme, anno2_theme_vectors in anno2_themes.items():
      s_time = time.time()
      cosine_sims = cosine_similarity(anno1_theme_vectors , anno2_theme_vectors)
      average_sim = np.average(cosine_sims)
      std_deviation = np.std(cosine_sims)
      global_average_sims.append({'anno1' : anno1 ,
                                  'anno2' : anno2 ,
                                  'anno1_theme' : anno1_theme ,
                                  'anno2_theme' : anno2_theme ,
                                  'average_sim' : average_sim ,
                                  'std_deviation' : std_deviation
                                  })
      print(f"Completed {ctr+1}/{total_combos} combinations.\nTotal time to calc : {time.time() - s_time} seconds. \n{global_average_sims[-1]}\n--------\n")
      # save for reference since this calculation runs much slower than for pacheco data
      pd.DataFrame(global_average_sims).to_csv('./dataset/fang_system/std_dev_aggregated_sims.csv', index=False)

Completed 1/15 combinations.
Total time to calc : 0.002836942672729492 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'AntiGunBan', 'average_sim': 0.303288, 'std_deviation': 0.13467766}
--------

Completed 1/15 combinations.
Total time to calc : 0.0022346973419189453 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'AntiWoke', 'average_sim': 0.27441308, 'std_deviation': 0.10325976}
--------

Completed 1/15 combinations.
Total time to calc : 0.010207891464233398 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'ProtectEnvironment', 'average_sim': 0.23161182, 'std_deviation': 0.11290237}
--------

Completed 1/15 combinations.
Total time to calc : 0.015947818756103516 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'CleanEnergyWorks', 'average_sim': 0.20948875, 'std_deviation': 0.120016314}
--------

Completed 1/15 combinations.
Total time to calc : 0.006051063537597656 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'ActionAgainstDemSpending', 'average_sim': 0.24456517, 'std_deviation': 0.11794432}
--------

Completed 1/15 combinations.
Total time to calc : 0.0009450912475585938 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'IndigenousAndBlackAdvocacy', 'average_sim': 0.26070142, 'std_deviation': 0.12135372}
--------

Completed 1/15 combinations.
Total time to calc : 0.004571199417114258 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'PassBidenAct', 'average_sim': 0.29205644, 'std_deviation': 0.111131676}
--------

Completed 1/15 combinations.
Total time to calc : 0.003693103790283203 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'AntiOilPolitician', 'average_sim': 0.22215632, 'std_deviation': 0.12764682}
--------

Completed 1/15 combinations.
Total time to calc : 0.0005922317504882812 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'AntiPropertyTax', 'average_sim': 0.25650907, 'std_deviation': 0.10648224}
--------

Completed 1/15 combinations.
Total time to calc : 0.0008821487426757812 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'ProUSOilIndustry', 'average_sim': 0.21307288, 'std_deviation': 0.1139604}
--------

Completed 1/15 combinations.
Total time to calc : 0.005523204803466797 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'ProtectRivers', 'average_sim': 0.3233897, 'std_deviation': 0.098835394}
--------

Completed 1/15 combinations.
Total time to calc : 0.007376909255981445 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'TPUSAAd', 'average_sim': 0.22915646, 'std_deviation': 0.09605802}
--------

Completed 1/15 combinations.
Total time to calc : 0.0021181106567382812 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'EVCharging', 'average_sim': 0.14358555, 'std_deviation': 0.09815125}
--------

Completed 1/15 combinations.
Total time to calc : 0.0017871856689453125 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiGunBan', 'anno2_theme': 'OilTheft', 'average_sim': 0.19378734, 'std_deviation': 0.08704679}
--------

Completed 1/15 combinations.
Total time to calc : 0.0042798519134521484 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'AntiGunBan', 'average_sim': 0.27441305, 'std_deviation': 0.10325976}
--------

Completed 1/15 combinations.
Total time to calc : 0.003638029098510742 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'AntiWoke', 'average_sim': 0.4159955, 'std_deviation': 0.17283872}
--------

Completed 1/15 combinations.
Total time to calc : 0.015012025833129883 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'ProtectEnvironment', 'average_sim': 0.18831533, 'std_deviation': 0.093117066}
--------

Completed 1/15 combinations.
Total time to calc : 0.013759374618530273 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'CleanEnergyWorks', 'average_sim': 0.14158681, 'std_deviation': 0.089630246}
--------

Completed 1/15 combinations.
Total time to calc : 0.004101753234863281 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'ActionAgainstDemSpending', 'average_sim': 0.1720275, 'std_deviation': 0.101217315}
--------

Completed 1/15 combinations.
Total time to calc : 0.0022819042205810547 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'IndigenousAndBlackAdvocacy', 'average_sim': 0.26539725, 'std_deviation': 0.105039656}
--------

Completed 1/15 combinations.
Total time to calc : 0.014805078506469727 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'PassBidenAct', 'average_sim': 0.22428992, 'std_deviation': 0.08868935}
--------

Completed 1/15 combinations.
Total time to calc : 0.00588226318359375 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'AntiOilPolitician', 'average_sim': 0.1687723, 'std_deviation': 0.10329004}
--------

Completed 1/15 combinations.
Total time to calc : 0.0021779537200927734 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'AntiPropertyTax', 'average_sim': 0.32706708, 'std_deviation': 0.15919083}
--------

Completed 1/15 combinations.
Total time to calc : 0.0018758773803710938 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'ProUSOilIndustry', 'average_sim': 0.13811922, 'std_deviation': 0.08764971}
--------

Completed 1/15 combinations.
Total time to calc : 0.00032782554626464844 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'ProtectRivers', 'average_sim': 0.31498158, 'std_deviation': 0.08871736}
--------

Completed 1/15 combinations.
Total time to calc : 0.0004742145538330078 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'TPUSAAd', 'average_sim': 0.23369591, 'std_deviation': 0.087347195}
--------

Completed 1/15 combinations.
Total time to calc : 0.001961946487426758 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'EVCharging', 'average_sim': 0.06640356, 'std_deviation': 0.056062702}
--------

Completed 1/15 combinations.
Total time to calc : 0.0008971691131591797 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'AntiWoke', 'anno2_theme': 'OilTheft', 'average_sim': 0.1717163, 'std_deviation': 0.07642495}
--------

Completed 1/15 combinations.
Total time to calc : 0.08502888679504395 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'AntiGunBan', 'average_sim': 0.23161185, 'std_deviation': 0.11290235}
--------

Completed 1/15 combinations.
Total time to calc : 0.012289047241210938 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'AntiWoke', 'average_sim': 0.18831533, 'std_deviation': 0.093117066}
--------

Completed 1/15 combinations.
Total time to calc : 0.04305267333984375 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'ProtectEnvironment', 'average_sim': 0.32964602, 'std_deviation': 0.14215763}
--------

Completed 1/15 combinations.
Total time to calc : 0.03858470916748047 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'CleanEnergyWorks', 'average_sim': 0.2755715, 'std_deviation': 0.12151666}
--------

Completed 1/15 combinations.
Total time to calc : 0.012382030487060547 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'ActionAgainstDemSpending', 'average_sim': 0.28751236, 'std_deviation': 0.12419524}
--------

Completed 1/15 combinations.
Total time to calc : 0.006145000457763672 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'IndigenousAndBlackAdvocacy', 'average_sim': 0.2293349, 'std_deviation': 0.11227268}
--------

Completed 1/15 combinations.
Total time to calc : 0.025880098342895508 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'PassBidenAct', 'average_sim': 0.3452584, 'std_deviation': 0.12080789}
--------

Completed 1/15 combinations.
Total time to calc : 0.04177999496459961 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'AntiOilPolitician', 'average_sim': 0.32772276, 'std_deviation': 0.12944356}
--------

Completed 1/15 combinations.
Total time to calc : 0.013547897338867188 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'AntiPropertyTax', 'average_sim': 0.22204094, 'std_deviation': 0.09124979}
--------

Completed 1/15 combinations.
Total time to calc : 0.044088125228881836 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'ProUSOilIndustry', 'average_sim': 0.26804224, 'std_deviation': 0.12441206}
--------

Completed 1/15 combinations.
Total time to calc : 0.004108905792236328 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'ProtectRivers', 'average_sim': 0.31601697, 'std_deviation': 0.117878444}
--------

Completed 1/15 combinations.
Total time to calc : 0.003743886947631836 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'TPUSAAd', 'average_sim': 0.18743162, 'std_deviation': 0.08697767}
--------

Completed 1/15 combinations.
Total time to calc : 0.0014090538024902344 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'EVCharging', 'average_sim': 0.17668484, 'std_deviation': 0.084797665}
--------

Completed 1/15 combinations.
Total time to calc : 0.00421595573425293 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ProtectEnvironment', 'anno2_theme': 'OilTheft', 'average_sim': 0.22579832, 'std_deviation': 0.095815375}
--------

Completed 1/15 combinations.
Total time to calc : 0.02380228042602539 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'AntiGunBan', 'average_sim': 0.20948872, 'std_deviation': 0.12001629}
--------

Completed 1/15 combinations.
Total time to calc : 0.07165098190307617 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'AntiWoke', 'average_sim': 0.14158683, 'std_deviation': 0.089630246}
--------

Completed 1/15 combinations.
Total time to calc : 0.03088212013244629 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'ProtectEnvironment', 'average_sim': 0.2755714, 'std_deviation': 0.12151666}
--------

Completed 1/15 combinations.
Total time to calc : 0.03151297569274902 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'CleanEnergyWorks', 'average_sim': 0.34454262, 'std_deviation': 0.12953624}
--------

Completed 1/15 combinations.
Total time to calc : 0.021851062774658203 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'ActionAgainstDemSpending', 'average_sim': 0.29935327, 'std_deviation': 0.12620951}
--------

Completed 1/15 combinations.
Total time to calc : 0.004208087921142578 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'IndigenousAndBlackAdvocacy', 'average_sim': 0.19270852, 'std_deviation': 0.11528487}
--------

Completed 1/15 combinations.
Total time to calc : 0.01243281364440918 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'PassBidenAct', 'average_sim': 0.3299478, 'std_deviation': 0.11320191}
--------

Completed 1/15 combinations.
Total time to calc : 0.006360054016113281 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'AntiOilPolitician', 'average_sim': 0.3218598, 'std_deviation': 0.119089484}
--------

Completed 1/15 combinations.
Total time to calc : 0.006415843963623047 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'AntiPropertyTax', 'average_sim': 0.21164982, 'std_deviation': 0.10237394}
--------

Completed 1/15 combinations.
Total time to calc : 0.005177974700927734 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'ProUSOilIndustry', 'average_sim': 0.2730086, 'std_deviation': 0.11946058}
--------

Completed 1/15 combinations.
Total time to calc : 0.0019130706787109375 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'ProtectRivers', 'average_sim': 0.23438057, 'std_deviation': 0.09774589}
--------

Completed 1/15 combinations.
Total time to calc : 0.006852149963378906 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'TPUSAAd', 'average_sim': 0.14175951, 'std_deviation': 0.084406614}
--------

Completed 1/15 combinations.
Total time to calc : 0.0036911964416503906 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'EVCharging', 'average_sim': 0.1644954, 'std_deviation': 0.073181614}
--------

Completed 1/15 combinations.
Total time to calc : 0.005334138870239258 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'CleanEnergyWorks', 'anno2_theme': 'OilTheft', 'average_sim': 0.24008678, 'std_deviation': 0.09175278}
--------

Completed 1/15 combinations.
Total time to calc : 0.005917072296142578 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'AntiGunBan', 'average_sim': 0.24456517, 'std_deviation': 0.11794432}
--------

Completed 1/15 combinations.
Total time to calc : 0.00984811782836914 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'AntiWoke', 'average_sim': 0.1720275, 'std_deviation': 0.10121732}
--------

Completed 1/15 combinations.
Total time to calc : 0.012464046478271484 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'ProtectEnvironment', 'average_sim': 0.28751233, 'std_deviation': 0.12419523}
--------

Completed 1/15 combinations.
Total time to calc : 0.012112855911254883 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'CleanEnergyWorks', 'average_sim': 0.29935342, 'std_deviation': 0.12620951}
--------

Completed 1/15 combinations.
Total time to calc : 0.004570960998535156 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'ActionAgainstDemSpending', 'average_sim': 0.40377504, 'std_deviation': 0.14550304}
--------

Completed 1/15 combinations.
Total time to calc : 0.0017659664154052734 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'IndigenousAndBlackAdvocacy', 'average_sim': 0.19503368, 'std_deviation': 0.11090926}
--------

Completed 1/15 combinations.
Total time to calc : 0.006922006607055664 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'PassBidenAct', 'average_sim': 0.33079454, 'std_deviation': 0.107010394}
--------

Completed 1/15 combinations.
Total time to calc : 0.0026128292083740234 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'AntiOilPolitician', 'average_sim': 0.31052586, 'std_deviation': 0.11509668}
--------

Completed 1/15 combinations.
Total time to calc : 0.002357959747314453 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'AntiPropertyTax', 'average_sim': 0.29177025, 'std_deviation': 0.11383431}
--------

Completed 1/15 combinations.
Total time to calc : 0.0013680458068847656 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'ProUSOilIndustry', 'average_sim': 0.3505042, 'std_deviation': 0.13582124}
--------

Completed 1/15 combinations.
Total time to calc : 0.0016307830810546875 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'ProtectRivers', 'average_sim': 0.2887381, 'std_deviation': 0.09492196}
--------

Completed 1/15 combinations.
Total time to calc : 0.002777099609375 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'TPUSAAd', 'average_sim': 0.14057106, 'std_deviation': 0.082345225}
--------

Completed 1/15 combinations.
Total time to calc : 0.0006568431854248047 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'EVCharging', 'average_sim': 0.17608167, 'std_deviation': 0.07563734}
--------

Completed 1/15 combinations.
Total time to calc : 0.0021429061889648438 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'ActionAgainstDemSpending', 'anno2_theme': 'OilTheft', 'average_sim': 0.28784314, 'std_deviation': 0.08749784}
--------

Completed 1/15 combinations.
Total time to calc : 0.0007030963897705078 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'IndigenousAndBlackAdvocacy', 'anno2_theme': 'AntiGunBan', 'average_sim': 0.26070142, 'std_deviation': 0.12135373}
--------

Completed 1/15 combinations.
Total time to calc : 0.0010540485382080078 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'IndigenousAndBlackAdvocacy', 'anno2_theme': 'AntiWoke', 'average_sim': 0.26539725, 'std_deviation': 0.105039656}
--------

Completed 1/15 combinations.
Total time to calc : 0.005373239517211914 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'IndigenousAndBlackAdvocacy', 'anno2_theme': 'ProtectEnvironment', 'average_sim': 0.2293349, 'std_deviation': 0.11227268}
--------

Completed 1/15 combinations.
Total time to calc : 0.0026569366455078125 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'IndigenousAndBlackAdvocacy', 'anno2_theme': 'CleanEnergyWorks', 'average_sim': 0.1927085, 'std_deviation': 0.11528487}
--------

Completed 1/15 combinations.
Total time to calc : 0.0040950775146484375 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'IndigenousAndBlackAdvocacy', 'anno2_theme': 'ActionAgainstDemSpending', 'average_sim': 0.19503367, 'std_deviation': 0.110909276}
--------

Completed 1/15 combinations.
Total time to calc : 0.0007059574127197266 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'IndigenousAndBlackAdvocacy', 'anno2_theme': 'IndigenousAndBlackAdvocacy', 'average_sim': 0.40211174, 'std_deviation': 0.19025713}
--------

Completed 1/15 combinations.
Total time to calc : 0.0032367706298828125 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'IndigenousAndBlackAdvocacy', 'anno2_theme': 'PassBidenAct', 'average_sim': 0.26476687, 'std_deviation': 0.10017483}
--------

Completed 1/15 combinations.
Total time to calc : 0.0013041496276855469 seconds.
{'anno1': 'async_1', 'anno2': 'async_1', 'anno1_theme': 'IndigenousAndBlackAdvocacy', 'anno2_theme': 'AntiOilPolitician', 'average_sim': 0.20063567, 'std_deviation': 0.12317555}
--------

Completed 1/15 combinations.

KeyboardInterrupt:

In [ ]:
# Read from csv
# global_average_sims = pd.read_csv('./dataset/fang_system/std_dev_aggregated_sims.csv')

In [ ]:
global_average_sims

[{'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'AntiGunBan',
  'average_sim': 0.303288,
  'std_deviation': 0.13467766},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'AntiWoke',
  'average_sim': 0.27441308,
  'std_deviation': 0.10325976},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'ProtectEnvironment',
  'average_sim': 0.23161182,
  'std_deviation': 0.11290237},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'CleanEnergyWorks',
  'average_sim': 0.20948875,
  'std_deviation': 0.120016314},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'ActionAgainstDemSpending',
  'average_sim': 0.24456517,
  'std_deviation': 0.11794432},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'IndigenousAndBlackAdvocacy',
  'average_sim': 0.26070142,
  'std_deviation': 0.12135372},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'PassBidenAct',
  'average_sim': 0.29205644,
  'std_deviation': 0.111131676},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'AntiOilPolitician',
  'average_sim': 0.22215632,
  'std_deviation': 0.12764682},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'AntiPropertyTax',
  'average_sim': 0.25650907,
  'std_deviation': 0.10648224},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'ProUSOilIndustry',
  'average_sim': 0.21307288,
  'std_deviation': 0.1139604},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'ProtectRivers',
  'average_sim': 0.3233897,
  'std_deviation': 0.098835394},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'TPUSAAd',
  'average_sim': 0.22915646,
  'std_deviation': 0.09605802},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'EVCharging',
  'average_sim': 0.14358555,
  'std_deviation': 0.09815125},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiGunBan',
  'anno2_theme': 'OilTheft',
  'average_sim': 0.19378734,
  'std_deviation': 0.08704679},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'AntiGunBan',
  'average_sim': 0.27441305,
  'std_deviation': 0.10325976},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'AntiWoke',
  'average_sim': 0.4159955,
  'std_deviation': 0.17283872},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'ProtectEnvironment',
  'average_sim': 0.18831533,
  'std_deviation': 0.093117066},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'CleanEnergyWorks',
  'average_sim': 0.14158681,
  'std_deviation': 0.089630246},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'ActionAgainstDemSpending',
  'average_sim': 0.1720275,
  'std_deviation': 0.101217315},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'IndigenousAndBlackAdvocacy',
  'average_sim': 0.26539725,
  'std_deviation': 0.105039656},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'PassBidenAct',
  'average_sim': 0.22428992,
  'std_deviation': 0.08868935},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'AntiOilPolitician',
  'average_sim': 0.1687723,
  'std_deviation': 0.10329004},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'AntiPropertyTax',
  'average_sim': 0.32706708,
  'std_deviation': 0.15919083},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'ProUSOilIndustry',
  'average_sim': 0.13811922,
  'std_deviation': 0.08764971},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'ProtectRivers',
  'average_sim': 0.31498158,
  'std_deviation': 0.08871736},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'TPUSAAd',
  'average_sim': 0.23369591,
  'std_deviation': 0.087347195},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'EVCharging',
  'average_sim': 0.06640356,
  'std_deviation': 0.056062702},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiWoke',
  'anno2_theme': 'OilTheft',
  'average_sim': 0.1717163,
  'std_deviation': 0.07642495},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'AntiGunBan',
  'average_sim': 0.23161185,
  'std_deviation': 0.11290235},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'AntiWoke',
  'average_sim': 0.18831533,
  'std_deviation': 0.093117066},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'ProtectEnvironment',
  'average_sim': 0.32964602,
  'std_deviation': 0.14215763},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'CleanEnergyWorks',
  'average_sim': 0.2755715,
  'std_deviation': 0.12151666},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'ActionAgainstDemSpending',
  'average_sim': 0.28751236,
  'std_deviation': 0.12419524},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'IndigenousAndBlackAdvocacy',
  'average_sim': 0.2293349,
  'std_deviation': 0.11227268},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'PassBidenAct',
  'average_sim': 0.3452584,
  'std_deviation': 0.12080789},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'AntiOilPolitician',
  'average_sim': 0.32772276,
  'std_deviation': 0.12944356},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'AntiPropertyTax',
  'average_sim': 0.22204094,
  'std_deviation': 0.09124979},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'ProUSOilIndustry',
  'average_sim': 0.26804224,
  'std_deviation': 0.12441206},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'ProtectRivers',
  'average_sim': 0.31601697,
  'std_deviation': 0.117878444},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'TPUSAAd',
  'average_sim': 0.18743162,
  'std_deviation': 0.08697767},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'EVCharging',
  'average_sim': 0.17668484,
  'std_deviation': 0.084797665},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ProtectEnvironment',
  'anno2_theme': 'OilTheft',
  'average_sim': 0.22579832,
  'std_deviation': 0.095815375},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'AntiGunBan',
  'average_sim': 0.20948872,
  'std_deviation': 0.12001629},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'AntiWoke',
  'average_sim': 0.14158683,
  'std_deviation': 0.089630246},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'ProtectEnvironment',
  'average_sim': 0.2755714,
  'std_deviation': 0.12151666},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'CleanEnergyWorks',
  'average_sim': 0.34454262,
  'std_deviation': 0.12953624},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'ActionAgainstDemSpending',
  'average_sim': 0.29935327,
  'std_deviation': 0.12620951},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'IndigenousAndBlackAdvocacy',
  'average_sim': 0.19270852,
  'std_deviation': 0.11528487},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'PassBidenAct',
  'average_sim': 0.3299478,
  'std_deviation': 0.11320191},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'AntiOilPolitician',
  'average_sim': 0.3218598,
  'std_deviation': 0.119089484},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'AntiPropertyTax',
  'average_sim': 0.21164982,
  'std_deviation': 0.10237394},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'ProUSOilIndustry',
  'average_sim': 0.2730086,
  'std_deviation': 0.11946058},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'ProtectRivers',
  'average_sim': 0.23438057,
  'std_deviation': 0.09774589},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'TPUSAAd',
  'average_sim': 0.14175951,
  'std_deviation': 0.084406614},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'EVCharging',
  'average_sim': 0.1644954,
  'std_deviation': 0.073181614},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'CleanEnergyWorks',
  'anno2_theme': 'OilTheft',
  'average_sim': 0.24008678,
  'std_deviation': 0.09175278},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'AntiGunBan',
  'average_sim': 0.24456517,
  'std_deviation': 0.11794432},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'AntiWoke',
  'average_sim': 0.1720275,
  'std_deviation': 0.10121732},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'ProtectEnvironment',
  'average_sim': 0.28751233,
  'std_deviation': 0.12419523},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'CleanEnergyWorks',
  'average_sim': 0.29935342,
  'std_deviation': 0.12620951},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'ActionAgainstDemSpending',
  'average_sim': 0.40377504,
  'std_deviation': 0.14550304},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'IndigenousAndBlackAdvocacy',
  'average_sim': 0.19503368,
  'std_deviation': 0.11090926},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'PassBidenAct',
  'average_sim': 0.33079454,
  'std_deviation': 0.107010394},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'AntiOilPolitician',
  'average_sim': 0.31052586,
  'std_deviation': 0.11509668},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'AntiPropertyTax',
  'average_sim': 0.29177025,
  'std_deviation': 0.11383431},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'ProUSOilIndustry',
  'average_sim': 0.3505042,
  'std_deviation': 0.13582124},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'ProtectRivers',
  'average_sim': 0.2887381,
  'std_deviation': 0.09492196},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'TPUSAAd',
  'average_sim': 0.14057106,
  'std_deviation': 0.082345225},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'EVCharging',
  'average_sim': 0.17608167,
  'std_deviation': 0.07563734},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'ActionAgainstDemSpending',
  'anno2_theme': 'OilTheft',
  'average_sim': 0.28784314,
  'std_deviation': 0.08749784},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'AntiGunBan',
  'average_sim': 0.26070142,
  'std_deviation': 0.12135373},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'AntiWoke',
  'average_sim': 0.26539725,
  'std_deviation': 0.105039656},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'ProtectEnvironment',
  'average_sim': 0.2293349,
  'std_deviation': 0.11227268},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'CleanEnergyWorks',
  'average_sim': 0.1927085,
  'std_deviation': 0.11528487},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'ActionAgainstDemSpending',
  'average_sim': 0.19503367,
  'std_deviation': 0.110909276},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'IndigenousAndBlackAdvocacy',
  'average_sim': 0.40211174,
  'std_deviation': 0.19025713},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'PassBidenAct',
  'average_sim': 0.26476687,
  'std_deviation': 0.10017483},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'AntiOilPolitician',
  'average_sim': 0.20063567,
  'std_deviation': 0.12317555},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'AntiPropertyTax',
  'average_sim': 0.1917084,
  'std_deviation': 0.1086743},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'ProUSOilIndustry',
  'average_sim': 0.204287,
  'std_deviation': 0.11027},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'ProtectRivers',
  'average_sim': 0.36656827,
  'std_deviation': 0.10688136},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'TPUSAAd',
  'average_sim': 0.32957092,
  'std_deviation': 0.12696853},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'EVCharging',
  'average_sim': 0.10385604,
  'std_deviation': 0.07662706},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'IndigenousAndBlackAdvocacy',
  'anno2_theme': 'OilTheft',
  'average_sim': 0.18364999,
  'std_deviation': 0.09038874},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'AntiGunBan',
  'average_sim': 0.29205638,
  'std_deviation': 0.11113167},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'AntiWoke',
  'average_sim': 0.22428992,
  'std_deviation': 0.08868935},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'ProtectEnvironment',
  'average_sim': 0.34525853,
  'std_deviation': 0.120807886},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'CleanEnergyWorks',
  'average_sim': 0.3299479,
  'std_deviation': 0.11320191},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'ActionAgainstDemSpending',
  'average_sim': 0.33079448,
  'std_deviation': 0.10701038},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'IndigenousAndBlackAdvocacy',
  'average_sim': 0.26476684,
  'std_deviation': 0.10017483},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'PassBidenAct',
  'average_sim': 0.4792595,
  'std_deviation': 0.14374356},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'AntiOilPolitician',
  'average_sim': 0.38487634,
  'std_deviation': 0.12177875},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'AntiPropertyTax',
  'average_sim': 0.25650528,
  'std_deviation': 0.0723828},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'ProUSOilIndustry',
  'average_sim': 0.29633915,
  'std_deviation': 0.10797427},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'ProtectRivers',
  'average_sim': 0.3965946,
  'std_deviation': 0.09242904},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'TPUSAAd',
  'average_sim': 0.19144522,
  'std_deviation': 0.06049576},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'EVCharging',
  'average_sim': 0.21550657,
  'std_deviation': 0.08419139},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'PassBidenAct',
  'anno2_theme': 'OilTheft',
  'average_sim': 0.21332048,
  'std_deviation': 0.07173093},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'AntiGunBan',
  'average_sim': 0.2221563,
  'std_deviation': 0.12764683},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'AntiWoke',
  'average_sim': 0.1687723,
  'std_deviation': 0.10329004},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'ProtectEnvironment',
  'average_sim': 0.32772273,
  'std_deviation': 0.12944354},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'CleanEnergyWorks',
  'average_sim': 0.32185987,
  'std_deviation': 0.11908948},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'ActionAgainstDemSpending',
  'average_sim': 0.31052583,
  'std_deviation': 0.115096696},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'IndigenousAndBlackAdvocacy',
  'average_sim': 0.20063567,
  'std_deviation': 0.12317555},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'PassBidenAct',
  'average_sim': 0.3848763,
  'std_deviation': 0.12177875},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'AntiOilPolitician',
  'average_sim': 0.42326128,
  'std_deviation': 0.15449733},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'AntiPropertyTax',
  'average_sim': 0.22786757,
  'std_deviation': 0.09901868},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'ProUSOilIndustry',
  'average_sim': 0.27416614,
  'std_deviation': 0.11623289},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'ProtectRivers',
  'average_sim': 0.3235676,
  'std_deviation': 0.13861194},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'TPUSAAd',
  'average_sim': 0.13133411,
  'std_deviation': 0.08222085},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'EVCharging',
  'average_sim': 0.12163559,
  'std_deviation': 0.05116731},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiOilPolitician',
  'anno2_theme': 'OilTheft',
  'average_sim': 0.23523508,
  'std_deviation': 0.096039325},
 {'anno1': 'async_1',
  'anno2': 'async_1',
  'anno1_theme': 'AntiPropertyTax',
  'anno2_theme': 'AntiGunBan',

In [ ]:
global_average_df = pd.DataFrame(global_average_sims)

### 4.b. Calculating Synchronous Group Average Cosine Similarities

In [ ]:
max_cosine_sims = []

for anno_1, anno_2 in itertools.permutations(synchronous_annotators, 2):
    filtered_df = global_average_df[
        (global_average_df["anno1"] == anno_1) & (global_average_df["anno2"] == anno_2)
    ]
    for anno_1_theme in filtered_df["anno1_theme"].unique():
        if (
            ("kmeans" not in anno_1_theme.lower())
            and ("unexplainable" not in anno_1_theme.lower())
            and ("topic" not in anno_1_theme.lower())
            and ("unknown" not in anno_1_theme.lower())
        ):
            theme_filtered_df = filtered_df[
                (filtered_df["anno1_theme"] == anno_1_theme)
                & ~(filtered_df["anno2_theme"].str.contains("Kmeans"))
                & ~(filtered_df["anno2_theme"].str.contains("Unknown"))
            ]
            max_cosine_sims.append(
                theme_filtered_df.loc[
                    (theme_filtered_df["average_sim"].idxmax())
                ].to_dict()
            )

res_df = pd.DataFrame(max_cosine_sims)

print("Synchronous Group Average Cosine Similarity")
print(f"Average Max Group Cosine Similarity: {res_df['average_sim'].mean():.2f}")
print(
    f"Standard Deviation of Group Cosine Similarity: { res_df['average_sim'].std():.2f}"
)

print(res_df.count())

Synchronous Group Average Cosine Similarity
Average Max Group Cosine Similarity: 0.43
Standard Deviation of Group Cosine Similarity: 0.14
anno1            19
anno2            19
anno1_theme      19
anno2_theme      19
average_sim      19
std_deviation    19
dtype: int64

### 4.c. Calculating Asynchronous Group Average Cosine Similarities

In [ ]:
max_cosine_sims = []

for anno_1, anno_2 in itertools.permutations(asynchronous_annotators, 2):
    filtered_df = global_average_df[
        (global_average_df["anno1"] == anno_1) & (global_average_df["anno2"] == anno_2)
    ]
    for anno_1_theme in filtered_df["anno1_theme"].unique():
        if (
            ("kmeans" not in anno_1_theme.lower())
            and ("unexplainable" not in anno_1_theme.lower())
            and ("topic" not in anno_1_theme.lower())
            and ("unknown" not in anno_1_theme.lower())
        ):
            theme_filtered_df = filtered_df[
                (filtered_df["anno1_theme"] == anno_1_theme)
                & ~(filtered_df["anno2_theme"].str.contains("Kmeans"))
                & ~(filtered_df["anno2_theme"].str.contains("Unknown"))
            ]
            max_cosine_sims.append(
                theme_filtered_df.loc[
                    (theme_filtered_df["average_sim"].idxmax())
                ].to_dict()
            )

res_df = pd.DataFrame(max_cosine_sims)


print("Asynchronous Group Average Cosine Similarity")
print(f"Average Max Group Cosine Similarity: {res_df['average_sim'].mean():.2f}")
print(
    f"Standard Deviation of Group Cosine Similarity: { res_df['average_sim'].std():.2f}"
)

print(res_df.count())

Asynchronous Group Average Cosine Similarity
Average Max Group Cosine Similarity: 0.46
Standard Deviation of Group Cosine Similarity: 0.16
anno1            42
anno2            42
anno1_theme      42
anno2_theme      42
average_sim      42
std_deviation    42
dtype: int64

____

## 5. Getting weights by percentile buckets

In [ ]:
results = []

for annotator, df in annotator2df.items():
    cosine_sims = []
    themes = []
    for i, theme in enumerate(df["name"].unique()):
        if (
            ("kmeans" not in theme.lower())
            and ("unexplainable" not in theme.lower())
            and ("topic" not in theme.lower())
            and ("unknown" not in theme.lower())
        ):
            result = {"annotator": annotator}
            ids = df[df["name"] == theme]["tweet_id"].tolist()
            result["theme"] = theme
            result["tweets"] = df[df["name"] == theme]["text"].tolist()
            result["weights"] = df[df["name"] == theme]["weight"].tolist()

            theme_vectors = sbert_vectors[ids]
            theme_centroid = np.average(theme_vectors, axis=0, keepdims=True)

            result["theme_centroid"] = theme_centroid
            result["theme_vectors"] = theme_vectors

            dot_prod = np.dot(theme_centroid, theme_vectors.T).squeeze(0)
            dot_prod = np.expand_dims(dot_prod, axis=-1)

            norm = np.linalg.norm(theme_vectors, axis=1, keepdims=True)
            cosine_sim = dot_prod / norm
            result["cosine_sim"] = cosine_sim.squeeze()
            results.append(result)

In [ ]:
quartile_map = {
    "0-25": (0, 25),
    "25-50": (25, 50),
    "50-75": (50, 75),
    "75-100": (75, 100),
}

quartile_results = {
    quartile: {'tweets': [],
              'vectors': [],
              'theme': [],
              'annotator': []}
    for quartile in quartile_map.keys()
}

for result in results:
    for quartile, (n, m) in quartile_map.items():
        low = np.percentile(result["weights"], n)
        high = np.percentile(result["weights"], m)
        
        quartile_indices = np.where((result["weights"] >= low) & (result["weights"] <= high))
        quartile_vectors = result["theme_vectors"][quartile_indices]
        quartile_tweets = np.array(result["tweets"])[quartile_indices]
        
        annotator = result["annotator"]
        theme = result["theme"]

        quartile_results[quartile]["tweets"].extend(quartile_tweets)
        quartile_results[quartile]["vectors"].extend(quartile_vectors)
        quartile_results[quartile]["theme"].extend([theme] * quartile_tweets.shape[0])
        quartile_results[quartile]["annotator"].extend([annotator] * quartile_tweets.shape[0])

quartile_dfs = {
    quartile: pd.DataFrame(data=quartile_data, columns=["theme", "annotator", "tweets"])
    for quartile, quartile_data in quartile_results.items()
}

    # m = np.percentile(result["weights"], 75)
    # top_25_indices = np.where(result["weights"] > m)
    # top_25_vectors = result["theme_vectors"][top_25_indices]
    # top_25_tweets = np.array(result["tweets"])[top_25_indices]
    # annotator = result["annotator"]
    # theme = result["theme"]

    # top_25_results["top_25_tweets"].extend(top_25_tweets)
    # top_25_results["top_25_vectors"].extend(top_25_vectors)
    # top_25_results["theme"].extend([theme] * top_25_tweets.shape[0])
    # top_25_results["annotator"].extend([annotator] * top_25_tweets.shape[0])


# top_25_df = pd.DataFrame(
#     top_25_results, columns=["theme", "annotator", "top_25_tweets"]
# )

### 4.a. Random Sampling rows for manual annotations

In [ ]:
for quartile, df in quartile_dfs.items():
    # Get unique themes in this quartile
    # themes = df['theme'].unique()
    async_themes = df[df['annotator'].isin(asynchronous_annotators)]['theme'].unique()
    sync_themes = df[df['annotator'].isin(synchronous_annotators)]['theme'].unique()
    
    # Calculate samples per theme (200 total / number of themes)
    # samples_per_theme = 200 // len(themes)
    # remaining_samples = 200 % len(themes)
    async_samples_per_theme = 50 // len(async_themes)
    async_remaining_samples = 50 % len(async_themes)
    sync_samples_per_theme = 52 // len(sync_themes)
    sync_remaining_samples = 52 % len(sync_themes)
    
    # Sample from synchronous annotators
    sync_samples = []
    for i, theme in enumerate(sync_themes):
        theme_df = df[(df['annotator'].isin(synchronous_annotators)) & (df['theme'] == theme)]
        n_samples = sync_samples_per_theme + (1 if i < sync_remaining_samples else 0)
        n_samples = min(n_samples, len(theme_df))  # Don't sample more than available
        if n_samples > 0:
            sync_samples.append(theme_df.sample(n=n_samples))
    
    sync_quartile = pd.concat(sync_samples, ignore_index=True)[['theme', 'tweets']]
    
    # Sample from asynchronous annotators
    async_samples = []
    for i, theme in enumerate(async_themes):
        theme_df = df[(df['annotator'].isin(asynchronous_annotators)) & (df['theme'] == theme)]
        n_samples = async_samples_per_theme + (1 if i < async_remaining_samples else 0)
        n_samples = min(n_samples, len(theme_df))  # Don't sample more than available
        if n_samples > 0:
            async_samples.append(theme_df.sample(n=n_samples))
    
    async_quartile = pd.concat(async_samples, ignore_index=True)[['theme', 'tweets']]
    
    # Save to CSV
    sync_quartile.to_csv(f'./dataset/generated_samples/fang_sync_sample_{quartile}_new.csv', index=False, sep='\t')
    async_quartile.to_csv(f'./dataset/generated_samples/fang_async_sample_{quartile}_new.csv', index=False, sep='\t')
    print(len(sync_quartile), len(async_quartile))

51 50
50 50
51 50
51 50

____

## 5. Calculating Intra- and Inter-cluster Similarity

In [ ]:
top_25_results = {}

for result in results: 

    top_25_results[result['theme']] = {}

    m = np.percentile(result['weights'] , 75)
    top_25_indices = np.where(result['weights']>=m)
    top_25_vectors = result['theme_vectors'][top_25_indices]
    top_25_tweets = np.array(result['tweets'])[top_25_indices]
    annotator=result['annotator']
    theme=result['theme']

    top_25_results[theme]['top_25_tweets'] = (top_25_tweets)
    top_25_results[theme]['top_25_vectors'] = (top_25_vectors )
    top_25_results[theme]['annotator'] = (annotator)

### 5.a. Calculating similarities for top 25th percentile clusters

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

top_25_average_sims = []

for anno_1_theme , anno1_top_25 in tqdm(top_25_results.items()): 
    for anno_2_theme , anno2_top_25 in top_25_results.items(): 

        anno1_top_25_vectors = anno1_top_25['top_25_vectors']
        anno2_top_25_vectors = anno2_top_25['top_25_vectors']

        cosine_sims = cosine_similarity(anno1_top_25_vectors , anno2_top_25_vectors)
        average_sim = np.average(cosine_sims)
        std_deviation = np.std(cosine_sims)

        top_25_average_sims.append({'anno_1' : anno1_top_25['annotator'] , 
                                   'anno_2' : anno2_top_25['annotator'], 
                                   'anno_1_theme' : anno_1_theme,
                                   'anno_2_theme' : anno_2_theme,
                                   'average_sim' : average_sim , 
                                   'std_dev_sim' : std_deviation})

  0%|          | 0/71 [00:00<?, ?it/s]

In [ ]:
top_25_average_df = pd.DataFrame(top_25_average_sims)
top_25_average_df

,anno_1,anno_2,anno_1_theme,anno_2_theme,average_sim,std_dev_sim
0,async_3,async_3,AntiGunBan,AntiGunBan,0.596259,0.171514
1,async_3,async_1,AntiGunBan,AntiWoke,0.386459,0.090362
2,async_3,async_1,AntiGunBan,ProtectEnvironment,0.237373,0.094159
3,async_3,async_1,AntiGunBan,CleanEnergyWorks,0.143717,0.076706
4,async_3,async_1,AntiGunBan,ActionAgainstDemSpending,0.244062,0.090942
...,...,...,...,...,...,...
5036,async_3,async_3,EnergyInfrastructureProjects,WaterPollutionAndContamination,0.182567,0.096527
5037,async_3,async_3,EnergyInfrastructureProjects,ProCleanEnergyPolitician,0.197540,0.093913
5038,async_3,async_3,EnergyInfrastructureProjects,TPUSALiveAd,0.108311,0.031367
5039,async_3,async_3,EnergyInfrastructureProjects,AntiLiberalSpending,0.093319,0.041961
5040,async_3,async_3,EnergyInfrastructureProjects,EnergyInfrastructureProjects,0.418450,0.304315

In [ ]:
top_25_intra_cluster_df = top_25_average_df[(top_25_average_df['anno_1']==top_25_average_df['anno_2']) & (top_25_average_df['anno_1_theme']==top_25_average_df['anno_2_theme'])]

### 5.b. Intra- and Inter-theme similarities for top 25th percentile subsets in synchronous and asynchronous experiments

In [ ]:
print(f"Synchronous top 25% intra theme similarity average: {top_25_intra_cluster_df[top_25_intra_cluster_df['anno_1'].isin(synchronous_annotators)]['average_sim'].mean():.2f}")
print(f"Synchronous top 25% intra theme similarity standard deviation: {top_25_intra_cluster_df[top_25_intra_cluster_df['anno_1'].isin(synchronous_annotators)]['average_sim'].std():.2f}")


print(f"Asynchronous top 25% intra theme similarity average: {top_25_intra_cluster_df[top_25_intra_cluster_df['anno_1'].isin(asynchronous_annotators)]['average_sim'].mean():.2f}")
print(f"Asynchronous top 25% intra theme similarity standard deviation: {top_25_intra_cluster_df[top_25_intra_cluster_df['anno_1'].isin(asynchronous_annotators)]['average_sim'].std():.2f}")

Synchronous top 25% intra theme similarity average: 0.72
Synchronous top 25% intra theme similarity standard deviation: 0.21
Asynchronous top 25% intra theme similarity average: 0.65
Asynchronous top 25% intra theme similarity standard deviation: 0.20

In [ ]:
top_25_intra_cluster_df = top_25_average_df[(top_25_average_df['anno_1']==top_25_average_df['anno_2']) & (top_25_average_df['anno_1_theme']!=top_25_average_df['anno_2_theme'])]

In [ ]:
print(f"Synchronous top 25% inter theme similarity average: {top_25_intra_cluster_df[top_25_intra_cluster_df['anno_1'].isin(synchronous_annotators)]['average_sim'].mean():.2f}")
print(f"Synchronous top 25% inter theme similarity standard deviation: {top_25_intra_cluster_df[top_25_intra_cluster_df['anno_1'].isin(synchronous_annotators)]['average_sim'].std():.2f}")


print(f"Asynchronous top 25% inter theme similarity average: {top_25_intra_cluster_df[top_25_intra_cluster_df['anno_1'].isin(asynchronous_annotators)]['average_sim'].mean():.2f}")
print(f"Asynchronous top 25% inter theme similarity standard deviation: {top_25_intra_cluster_df[top_25_intra_cluster_df['anno_1'].isin(asynchronous_annotators)]['average_sim'].std():.2f}")

Synchronous top 25% inter theme similarity average: 0.26
Synchronous top 25% inter theme similarity standard deviation: 0.09
Asynchronous top 25% inter theme similarity average: 0.26
Asynchronous top 25% inter theme similarity standard deviation: 0.08

### 5.c. Intra- and Inter-theme similarities for whole set in synchronous and asynchronous experiments

In [ ]:
global_average_df = pd.DataFrame(global_average_sims)

intra_global_average_df = global_average_df[(global_average_df['anno1']==global_average_df['anno2']) & (global_average_df['anno1_theme']==global_average_df['anno2_theme'])] 


print(f"Synchronous global intra theme similarity average: {intra_global_average_df[intra_global_average_df['anno1'].isin(synchronous_annotators)]['average_sim'].mean():.2f}")
print(f"Synchronous global intra theme similarity standard deviation: {intra_global_average_df[intra_global_average_df['anno1'].isin(synchronous_annotators)]['average_sim'].std():.2f}")


print(f"Asynchronous global intra theme similarity average: {intra_global_average_df[intra_global_average_df['anno1'].isin(asynchronous_annotators)]['average_sim'].mean():.2f}")
print(f"Asynchronous global intra theme similarity standard deviation: {intra_global_average_df[intra_global_average_df['anno1'].isin(asynchronous_annotators)]['average_sim'].std():.2f}")

Synchronous global intra theme similarity average: 0.57
Synchronous global intra theme similarity standard deviation: 0.23
Asynchronous global intra theme similarity average: 0.50
Asynchronous global intra theme similarity standard deviation: 0.19

In [ ]:
inter_global_avg_df = global_average_df[(global_average_df['anno1']==global_average_df['anno2']) & (global_average_df['anno1_theme']!=global_average_df['anno2_theme'])] 

print(f"Synchronous global inter theme similarity average: {inter_global_avg_df[inter_global_avg_df['anno1'].isin(synchronous_annotators)]['average_sim'].mean():.2f}")
print(f"Synchronous global inter theme similarity standard deviation: {inter_global_avg_df[inter_global_avg_df['anno1'].isin(synchronous_annotators)]['average_sim'].std():.2f}")


print(f"Asynchronous global inter theme similarity average: {inter_global_avg_df[inter_global_avg_df['anno1'].isin(asynchronous_annotators)]['average_sim'].mean():.2f}")
print(f"Asynchronous global inter theme similarity standard deviation: {inter_global_avg_df[inter_global_avg_df['anno1'].isin(asynchronous_annotators)]['average_sim'].std():.2f}")

Synchronous global inter theme similarity average: 0.25
Synchronous global inter theme similarity standard deviation: 0.08
Asynchronous global inter theme similarity average: 0.24
Asynchronous global inter theme similarity standard deviation: 0.07